services:
  rwtf_nginx:
    depends_on:
      - webapp
    networks:
      - rwtf_network
  webapp:
    build: webapp
    volumes:
      - webapp-content:/out
  server:
    networks:
      - rwtf_network
  mariadb:
    networks:
      - rwtf_network

networks:
  rwtf_network:
    external: true
