services:
  rwtf_nginx:
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.debug.conf:/etc/nginx/conf.d/default.conf
  server:
    ports:
      - 8080:8080
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=myuser
      - PMA_PASSWORD=mypassword
      - TZ=Europe/Berlin
    ports:
      - 8081:80
