services:
  rwtf_nginx:
    depends_on:
      - webapp
      - server
    networks:
      - rwtf_network
  screenshot:
    networks:
      - rwtf_network
  webapp:
    build: webapp
    volumes:
      - webapp-content:/out
  server:
    user: 1000:1000
    networks:
      - rwtf_network
  mariadb:
    user: 1000:1000
    networks:
      - rwtf_network

networks:
  rwtf_network:
    external: true
